imap_server = "imap.gmail.com"
imap_port = 993
imap_username = "@gmail.com"
imap_password = ""
discord_webhook_url = ""

# Ignore emails from these senders (exact match or partial match)
ignored_senders = [
    "no-reply@accounts.google.com"
]

# Ignore emails with these subjects (partial match)
ignored_subjects = [
    "Security Alert",
    "보안"
]
